version: '3.8'

services:
  mongodb-local:
    image: mongo:7.0.5
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
    networks:
      - comp3133-local

networks:
  comp3133-local:
